/// Renders the whole parity review corpus (curated samples + the largest
/// upstream fixture per diagram family) through the real Flutter pipeline and
/// asserts each one produces a usable scene.
///
/// This is the part of the old `parity_review_test.dart` with test value: it
/// catches parse/layout regressions across every diagram family on a plain
/// `flutter test`, without writing the ~9 MB review corpus. The corpus itself
/// is generated by `apps/demo/tool/parity_review_test.dart`.
library;

import 'package:flutter_test/flutter_test.dart';
import 'package:mermaid_core/mermaid_core.dart' as core;
import 'package:mermaid_flutter/mermaid_flutter.dart';

import 'support/parity_corpus.dart';
import 'support/workspace.dart';

void main() {
  TestWidgetsFlutterBinding.ensureInitialized();

  final cases = loadParityCases(workspaceRoot());

  for (final entry in cases) {
    test('renders ${entry.id}', () {
      final scene = const core.Mermaid(
        measurer: FlutterTextMeasurer(),
      ).render(entry.source);
      expect(
        scene.size.width,
        _positiveFinite,
        reason: '${entry.origin} produced a degenerate width',
      );
      expect(
        scene.size.height,
        _positiveFinite,
        reason: '${entry.origin} produced a degenerate height',
      );
    });
  }
}

final Matcher _positiveFinite = predicate<double>(
  (value) => value.isFinite && value > 0,
  'a positive finite size',
);
