name: _mermaid_dart_workspace
publish_to: none
environment:
  sdk: ^3.12.0
workspace:
  - packages/mermaid_core
  - packages/mermaid_flutter
  - packages/mermaid_samples
  - apps/demo
  - apps/flutter_embed
  - apps/website
